name: Build and Push Docker Image

on:
  push:
    branches:
      - CI/CD

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion au registre
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Étape 3 : Construction de l'image Docker
      - name: Build Docker image
        run: docker build -t ghcr.io/martinquivron/final-project-cloud-computing/my-app:latest .

      # Étape 4 : Pousser l'image
      - name: Push Docker image
        run: docker push ghcr.io/martinquivron/final-project-cloud-computing/my-app:latest
