name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_project:
    uses: ./.github/workflows/build.yml
    with:
      python-version: "3.12"

  lint_and_test:
    needs: build_project
    uses: ./.github/workflows/lint_test.yml
    with:
      python-version: "3.12" #flake8 installed in the virtual environment
  
  codeql_analysis:
    uses: ./.github/workflows/analysis.yml
    with:
      run_codeql: true

  docker_build_test:
    uses: ./.github/workflows/build_image.yml
    with:
      docker_context: .
      dockerfile: ./Dockerfile
      image_name: test_image
      tags: |
        type=ref,event=branch
        type=raw,value=latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  feature_lint_and_test:
    uses: ./.github/workflows/lint_test.yml
    with:
      python-version: "3.12"

  feature_codeql_analysis:
    needs: feature_lint_and_test
    uses: ./.github/workflows/analysis.yml
    with:
      run_codeql: true

