name: Test Workflow

on:
  push:
    branches:
      - CI/CD
  pull_request:
    branches:
      - main

jobs:
  build_project:
    uses: ./.github/workflows/build.yml
    with:
      python-version: "3.12"

  lint_and_test:
    needs: build_project
    uses: ./.github/workflows/lint_test.yml
    with:
      python-version: "3.12" #flake8 installed in the virtual environment
  
  codeql_analysis:
    uses: ./.github/workflows/analysis.yml
    with:
      run_codeql: true


